[[main]]
none = "none"

[[main]]
name = "Work"
pre = "blogger"
url = "/work/"
identifier = "VaYIUAQowd"
weight = 9999

[[main]]
name = "Sports"
pre = "heart"
url = "/sports/"
identifier = "qPYLstBD77"
weight = 9999

[[footer]]
none = "none"
